import {pizzas} from '@/data'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

const About = () => {
  return (
    <>
      <Head>
        <title>About pags</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ota">
        {pizzas?.map((el) => {
          return (
            <Link href={`/pizza/${el.id}`} key={el.id} className="card">
              <Image src={el.img} fill/>  
                <h2>{el.name}</h2>
                <p>{el.dasc}</p>
            </Link>
          );
        })}
        </div>
    </>
  )
}

export default About